@startuml
package command {
  interface ICommand {
    +~ICommand()
  }
  class NullCommand implements ICommand
  class CreateDatabaseCommand implements ICommand
}

package input {
  interface IInput {
    +~IInput()
    +std::unique_ptr<ICommand> getCommand()
  }
  package cli {
    class CommandLineArgument {
      +CommandLineArgument(std::string argument)
      +<<friend>> bool operator==(...)
      -std::string _argument
    }
  }
}

IInput --> ICommand : creates
@enduml
